// Sound-effect cues. Each component exports a `cues` function next to it that reuses the
// component's own timing helpers, so sounds are in sync by construction.
import React from "react";
import { Html5Audio, Sequence, staticFile } from "remotion";
import { brand } from "../brand";
import manifest from "../../public/sfx/manifest.json";

/** Generated by scripts/gen_sfx.py; see the README sound table for what each one means. */
export type SfxName = keyof typeof manifest;

export interface Cue {
  /** Frame relative to the start of the scene (or composition, once offset). */
  frame: number;
  sound: SfxName;
  /** Extra gain multiplier (default 1). */
  gain?: number;
  /**
   * Which take to play. For "note" this is the step index (rising scale). Omit it and multi-take
   * sounds rotate through their takes so repeats don't sound mechanical.
   */
  variant?: number;
}

export interface CueContext {
  fps: number;
  durationInFrames: number;
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type CueFn<P = any> = (props: P, ctx: CueContext) => Cue[];

const takes = (sound: SfxName): number[] => manifest[sound];

/** Ordered-step helper: step i plays note i of the rising pentatonic scale (wraps after the top). */
export const noteFor = (i: number) => ({ sound: "note" as const, variant: i % takes("note").length });

/** Minimum frames between two plays of the same sound (brand.audio.minGapMs overrides dedupeMs). */
export const minGapFrames = (sound: SfxName, fps: number): number => {
  const overrides = brand.audio.minGapMs as Partial<Record<SfxName, number>>;
  return ((overrides[sound] ?? brand.audio.dedupeMs) / 1000) * fps;
};

/** Smallest distance in frames between consecutive cues of one sound (Infinity if < 2). */
export const tightestGap = (cues: Cue[], sound: SfxName): number => {
  const f = cues.filter((c) => c.sound === sound).map((c) => c.frame).sort((a, b) => a - b);
  let g = Infinity;
  for (let i = 1; i < f.length; i++) g = Math.min(g, f[i] - f[i - 1]);
  return g;
};

/** When several cues land together, only the most meaningful one plays (earlier = wins). */
const PRIORITY: SfxName[] = [
  "outro",
  "chime",
  "ding",
  "buzz",
  "thud",
  "sparkle",
  "whoosh",
  "glide",
  "swoosh",
  "slide",
  "snap",
  "note",
  "blip",
  "click",
  "pop",
  "type",
  "tick",
];
const SIMULTANEOUS_MS = 100;

/** Collapse cues within SIMULTANEOUS_MS of each other to the highest-priority one. */
const onePerMoment = (sorted: Cue[], fps: number): Cue[] => {
  const win = (SIMULTANEOUS_MS / 1000) * fps;
  const out: Cue[] = [];
  for (const c of sorted) {
    const prev = out[out.length - 1];
    if (prev && c.frame - prev.frame <= win) {
      if (PRIORITY.indexOf(c.sound) < PRIORITY.indexOf(prev.sound)) out[out.length - 1] = { ...c, frame: prev.frame };
    } else out.push(c);
  }
  return out;
};

/**
 * Final mix: one sound per moment, then drop repeats of the same sound closer than its
 * minimum gap, and anything outside [0, end).
 */
export const dedupe = (cues: Cue[], fps: number, endFrame: number): Cue[] => {
  const last: Partial<Record<SfxName, number>> = {};
  const sorted = [...cues].filter((c) => c.frame >= 0 && c.frame < endFrame).sort((a, b) => a.frame - b.frame);
  const turn: Partial<Record<SfxName, number>> = {};
  return onePerMoment(sorted, fps)
    .filter((c) => {
      const prev = last[c.sound];
      if (prev !== undefined && c.frame - prev < minGapFrames(c.sound, fps)) return false;
      last[c.sound] = c.frame;
      return true;
    })
    .map((c) => {
      if (c.variant !== undefined) return c;
      const k = turn[c.sound] ?? 0;
      turn[c.sound] = k + 1;
      return { ...c, variant: k % takes(c.sound).length };
    });
};

export const SfxTrack: React.FC<{ cues: Cue[]; fps: number }> = ({ cues, fps }) => {
  if (!brand.audio.sfxEnabled) return null;
  return (
    <>
      {cues.map((c, i) => (
        <Sequence
          key={i}
          from={Math.round(c.frame)}
          durationInFrames={Math.ceil(takes(c.sound)[c.variant ?? 0] * fps) + 1}
          name={`sfx · ${c.sound}-${c.variant ?? 0}`}
          layout="none"
        >
          <Html5Audio
            src={staticFile(`sfx/${c.sound}-${c.variant ?? 0}.wav`)}
            volume={Math.min(1, brand.audio.sfxVolume * brand.audio.mix[c.sound] * (c.gain ?? 1))}
          />
        </Sequence>
      ))}
    </>
  );
};
